// <auto-generated />
using System;
using CoreAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260112121141_FixedNormalizedNameInRoles")]
    partial class FixedNormalizedNameInRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreAPI.Models.Account", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("AccountTypeId")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<string>("PerformBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.HasKey("TenantId", "CustomerId", "AccountTypeId");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PerformBy");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CustomerId", "AccountTypeId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("CoreAPI.Models.AccountType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("PerformBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("PerformBy");

                    b.HasIndex("TenantId");

                    b.HasIndex("IsActive", "IsDeleted");

                    b.HasIndex("Name", "TenantId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("AccountTypes", (string)null);
                });

            modelBuilder.Entity("CoreAPI.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<string>("PerformBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("PerformBy");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("CoreAPI.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PerformBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.HasIndex("PerformBy");

                    b.HasIndex("TenantId")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique()
                        .HasFilter("[Id] <> '' AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasFilter("[Name] <> '' AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique()
                        .HasFilter("[NormalizedName] <> '' AND [IsDeleted] = 0");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("CoreAPI.Models.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("PerformBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<byte>("Status")
                        .HasColumnType("TINYINT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("PerformBy");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("[Slug] <> '' AND  [Slug] IS NOT NULL AND [IsDeleted] = 0");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("CoreAPI.Models.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("AccountTypeId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.Property<string>("PerformBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Reason")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("TransactionTypeId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("PerformBy");

                    b.HasIndex("ReferenceId");

                    b.HasIndex("TransactionTypeId");

                    b.HasIndex("TenantId", "CustomerId", "AccountTypeId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("CoreAPI.Models.TransactionType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<bool>("AllowNegative")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<int>("Multiplier")
                        .HasColumnType("INT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("PerformBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("PerformBy");

                    b.HasIndex("TenantId");

                    b.HasIndex("IsActive", "IsDeleted");

                    b.HasIndex("Name", "TenantId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("TransactionTypes");
                });

            modelBuilder.Entity("CoreAPI.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(10)")
                        .HasDefaultValue("Local");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<string>("PerformBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("DATETIMEOFFSET(3)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PerformBy");

                    b.HasIndex("TenantId")
                        .HasFilter("[TenantId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasFilter("[Email] <> '' AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique()
                        .HasFilter("[TenantId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "UserName")
                        .IsUnique()
                        .HasFilter("[UserName] <> '' AND [IsDeleted] = 0");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CoreAPI.Models.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("RoleId")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId", "TenantId");

                    b.HasIndex("UserId", "TenantId");

                    b.HasIndex("UserId", "RoleId", "TenantId")
                        .IsUnique();

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("CoreAPI.Models.Account", b =>
                {
                    b.HasOne("CoreAPI.Models.AccountType", "AccountType")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreAPI.Models.Customer", "Customer")
                        .WithMany("Accounts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreAPI.Models.User", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformBy");

                    b.HasOne("CoreAPI.Models.Tenant", "Tenant")
                        .WithMany("Accounts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountType");

                    b.Navigation("Customer");

                    b.Navigation("Performer");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CoreAPI.Models.AccountType", b =>
                {
                    b.HasOne("CoreAPI.Models.User", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformBy");

                    b.HasOne("CoreAPI.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Performer");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CoreAPI.Models.Customer", b =>
                {
                    b.HasOne("CoreAPI.Models.User", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformBy");

                    b.HasOne("CoreAPI.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreAPI.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("CoreAPI.Models.Customer", "UserId");

                    b.Navigation("Performer");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreAPI.Models.Role", b =>
                {
                    b.HasOne("CoreAPI.Models.User", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformBy");

                    b.HasOne("CoreAPI.Models.Tenant", "Tenant")
                        .WithMany("Roles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Performer");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CoreAPI.Models.Tenant", b =>
                {
                    b.HasOne("CoreAPI.Models.User", "PerformByUser")
                        .WithMany()
                        .HasForeignKey("PerformBy");

                    b.OwnsOne("CoreAPI.Models.AccountSetting", "Setting", b1 =>
                        {
                            b1.Property<string>("TenantId")
                                .HasColumnType("VARCHAR(100)");

                            b1.Property<int>("ExpiryDays")
                                .HasColumnType("int");

                            b1.Property<int>("PointPerDollar")
                                .HasColumnType("int");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.Navigation("PerformByUser");

                    b.Navigation("Setting");
                });

            modelBuilder.Entity("CoreAPI.Models.Transaction", b =>
                {
                    b.HasOne("CoreAPI.Models.User", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformBy");

                    b.HasOne("CoreAPI.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("ReferenceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CoreAPI.Models.TransactionType", "TransactionType")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreAPI.Models.Account", null)
                        .WithMany("Transactions")
                        .HasForeignKey("TenantId", "CustomerId", "AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Performer");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("CoreAPI.Models.TransactionType", b =>
                {
                    b.HasOne("CoreAPI.Models.User", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformBy");

                    b.HasOne("CoreAPI.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Performer");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CoreAPI.Models.User", b =>
                {
                    b.HasOne("CoreAPI.Models.User", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformBy");

                    b.HasOne("CoreAPI.Models.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Performer");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CoreAPI.Models.UserRole", b =>
                {
                    b.HasOne("CoreAPI.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreAPI.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreAPI.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("CoreAPI.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CoreAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CoreAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CoreAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoreAPI.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CoreAPI.Models.AccountType", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("CoreAPI.Models.Customer", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("CoreAPI.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CoreAPI.Models.Tenant", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Roles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CoreAPI.Models.TransactionType", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CoreAPI.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
